### PR TITLE
Reproducible Build

### PR DESCRIPTION
**Pull request by mrerrormessage**
Be able to build all dependencies to run this model from within this repository. Probably using `make`.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
This should maybe be merged into tpl-reporting instead of master, but maybe tpl-reporting should be merged into master first?

**Comment by arthurhjorth** [comment]
TPL will not be merged in - it's a special branch for this project only.
Not sure how that affects the 'make'stuff, but lemme know if you have any
questions.

**Comment by qiemem** [comment]
@arthurhjorth has the right of this. This must use tpl-reporting, and tpl-reporting cannot be merged into master. @arthurhjorth did you get a chance to try this out? I'd like to merge it into master before we do anything else. It was working for @cbradyatinquire.

**Comment by arthurhjorth** [comment]
Hi guys,

This worked perfectly for me, so if that was the final test, this seems
ready for merging onto master.
- Arthur

On Tue, Apr 28, 2015 at 7:38 PM, Bryan Head notifications@github.com
wrote:

> @arthurhjorth https://github.com/arthurhjorth has the right of this.
> This must use tpl-reporting, and tpl-reporting cannot be merged into
> master. @arthurhjorth https://github.com/arthurhjorth did you get a
> chance to try this out? I'd like to merge it into master before we do
> anything else. It was working for @cbradyatinquire
> https://github.com/cbradyatinquire.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arthurhjorth/LevelSpaceXWGUI/pull/16#issuecomment-97272652
> .

## 

## 

Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning http://ccl.northwestern.edu/
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by qiemem** [comment]
Merged!

**Pull request merged**
