### PR TITLE
Up down arrows lost when loading new NetLogo model

### PR DESCRIPTION
**Pull request by mrerrormessage**
before loading:
screen shot 2015-05-05 at 12 14 09 am

after loading:
screen shot 2015-05-05 at 12 14 17 am

### CODE REVIEW

**Comment by cbradyatinquire** [comment]
I think this might just be due to a long name in the loaded NetLogo model.

**Comment by mrerrormessage** [comment]
Yes, that's what it looks like to me. You can see the border at the right. Is the desired solution here a change in the LSWidgets code to ensure that the column spacing preserves the up/down buttons, or a change in the NetLogo model to truncate too-long names before they get added?

**Comment by qiemem** [comment]
For this and #34, I was wondering if we wanted to throw `JScrollPane around the left part of the relationship widget (everything besides the arrows) so that people could scroll around inside them. That way, we don't have to worry about these kind of sizing issues.

**Comment by cbradyatinquire** [comment]
Hi -- My thought is that we should NOT do this in the short term at least.  Adding another level of scrolling is likely to make the UI feel more complex, and if we can mostly or completely avoid the problem by naming of our models, we might want to avoid adding visual complexity in the short term.
-c

**Comment by arthurhjorth** [comment]
@mrerrormessage would this be the worst time ever to ask that the buttons are just moved down next to the other buttons? (that would solve this too,as far as I can tell.)

**Comment by mrerrormessage** [comment]
That would actually be really easy to do. I'll hopefully have a PR up shortly.

**Comment by arthurhjorth** [comment]
Awesome!

On Tue, May 5, 2015 at 12:32 PM, Robert Grider notifications@github.com
wrote:

> That would actually be really easy to do. I'll hopefully have a PR up
> shortly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arthurhjorth/LevelSpaceXWGUI/issues/41#issuecomment-99153030
> .

## 

## 

Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning http://ccl.northwestern.edu/
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by mrerrormessage** [comment]
Do we want to truncate the text displayed in the comboboxes? Have it read `first part of text ...` if the name goes past a certain number of characters? The values returned from the combo box would still be the whole string. @arthurhjorth ? @cbradyatinquire ?

**Comment by arthurhjorth** [comment]
that would be an OK compromise for me

**Comment by mrerrormessage** [comment]
screen shot 2015-05-05 at 1 08 49 pm
See also https://github.com/qiemem/LSWidgets/compare/wip-change-relationship-widget?expand=1

**Pull request merged**
