### PR TITLE
Consistently use agent to lookup args

### PR DESCRIPTION
**Pull request by qiemem**
Not crazy happy with this fix, but not sure if I'll be able to improve it tonight.

### CODE REVIEW

**Comment by arthurhjorth** [comment]
All of the changes look good to me. If this catches all of the occurrences of the bad lookup, then this should be it.  Want me to merge?

**Comment by qiemem** [comment]
If you'd like to test it first:

```
git fetch
git checkout origin/arg-fix
```

and then

```
git checkout master
```

to get back. If you don't care to do that, sure, go ahead and merge it.

**Comment by arthurhjorth** [comment]
haha, is this your pedagogical way of making me use command line instead of
the Desktop client?

On Wed, May 6, 2015 at 6:31 PM, Bryan Head notifications@github.com wrote:

> If you'd like to test it first:
> 
> git fetch
> git checkout origin/arg-fix
> 
> and then
> 
> git checkout master
> 
> to get back. If you don't care to do that, sure, go ahead and merge it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arthurhjorth/LevelSpaceXWGUI/pull/58#issuecomment-99643456
> .

## 

## 

Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning http://ccl.northwestern.edu/
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by qiemem** [comment]
Uh oh, he's onto me.

**Comment by arthurhjorth** [comment]
Tried it (without using the command line a single time), and it looks good to me.

**Comment by qiemem** [comment]
Cool. You sure you didn't revert a bunch of fixes again? ;)

Merge away.

**Comment by arthurhjorth** [comment]
I'm sure i did

**Pull request merged**
